version: "3.3"
services:
    nginx:
        restart: unless-stopped
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
        volumes:
            - ./.docker/nginx/conf.d:/etc/nginx/conf.d
            - ./code/dist:/app/
        command: /bin/sh -c "nginx -g 'daemon off;'"
        env_file:
            - .env
        ports:
            - ${BLK_NGINX_PORT}:80
        depends_on:
            - nodejs

    nodejs:
        build:
            context: .
            dockerfile: .docker/nodejs/Dockerfile
        volumes:
            - ./code/:/app/
        command: /bin/sh -c 'npm ci && npm run build'
