version: "3.8"
services:
    nginx:
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/production/nginx.docker
        volumes:
            - ./docker/development/nginx/conf.d:/etc/nginx/conf.d
            - ./code/:/app/
        env_file:
            - .env
        ports:
            - ${BLK_NGINX_PORT}:80
        depends_on:
            - vuejs

    vuejs:
        build:
            context: docker/development
            dockerfile: vuejs.docker
        working_dir: /app
        volumes:
            - ./code/:/app/
        env_file:
            - .env
        ports:
            - 8080:8080
